require('dotenv').config({ path: '.env.local' });
const { createClient } = require('@supabase/supabase-js');

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

const books = [
  {
    title: 'The Midnight Library',
    author: 'Matt Haig',
    description: 'Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.',
    price: 19500,
    original_price: 28500,
    isbn: '9780525559474',
    genre: 'Fiction',
    publisher: 'Viking',
    published_year: 2020,
    pages: 304,
    language: 'English',
    condition: 'like-new',
    cover_image: 'https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg',
    stock: 15,
    rating: 4.5,
    review_count: 2847,
    featured: true,
    bestseller: true,
    tags: ['contemporary', 'philosophy', 'self-discovery'],
  },
  {
    title: 'Atomic Habits',
    author: 'James Clear',
    description: 'No matter your goals, Atomic Habits offers a proven framework for improving—every day. James Clear reveals practical strategies to form good habits and break bad ones.',
    price: 22500,
    original_price: 33000,
    isbn: '9780735211292',
    genre: 'Self-Help',
    publisher: 'Avery',
    published_year: 2018,
    pages: 320,
    language: 'English',
    condition: 'new',
    cover_image: 'https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg',
    stock: 30,
    rating: 4.8,
    review_count: 5621,
    featured: true,
    bestseller: true,
    tags: ['productivity', 'habits', 'self-improvement'],
  },
  {
    title: 'Where the Crawdads Sing',
    author: 'Delia Owens',
    description: 'A beautiful, haunting novel of suspense, secrets, and survival set in the wild marshlands of the American South.',
    price: 16500,
    original_price: 25500,
    isbn: '9780735224292',
    genre: 'Fiction',
    publisher: "G.P. Putnam's Sons",
    published_year: 2018,
    pages: 384,
    language: 'English',
    condition: 'good',
    cover_image: 'https://covers.openlibrary.org/b/isbn/9780735224292-L.jpg',
    stock: 20,
    rating: 4.7,
    review_count: 4102,
    featured: true,
    bestseller: true,
    tags: ['mystery', 'coming-of-age', 'southern'],
  },
  {
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    description: 'A magical story about following your dreams. Santiago, an Andalusian shepherd boy, journeys to Egypt in search of a worldly treasure.',
    price: 15000,
    original_price: 22500,
    isbn: '9780062315007',
    genre: 'Fiction',
    publisher: 'HarperOne',
    published_year: 1988,
    pages: 208,
    language: 'English',
    condition: 'good',
    cover_image: 'https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg',
    stock: 25,
    rating: 4.6,
    review_count: 8934,
    featured: false,
    bestseller: true,
    tags: ['adventure', 'philosophy', 'inspirational'],
  },
  {
    title: 'Educated',
    author: 'Tara Westover',
    description: 'A memoir about a young woman who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University.',
    price: 18000,
    original_price: 25500,
    isbn: '9780399590504',
    genre: 'Biography',
    publisher: 'Random House',
    published_year: 2018,
    pages: 352,
    language: 'English',
    condition: 'like-new',
    cover_image: 'https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg',
    stock: 12,
    rating: 4.7,
    review_count: 3215,
    featured: true,
    bestseller: false,
    tags: ['memoir', 'education', 'family'],
  },
  {
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    description: "A groundbreaking narrative of humanity's creation and evolution that explores how biology and history have defined us.",
    price: 21000,
    original_price: 30000,
    isbn: '9780062316097',
    genre: 'History',
    publisher: 'Harper',
    published_year: 2011,
    pages: 464,
    language: 'English',
    condition: 'new',
    cover_image: 'https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg',
    stock: 18,
    rating: 4.6,
    review_count: 7421,
    featured: true,
    bestseller: true,
    tags: ['history', 'anthropology', 'science'],
  },
  {
    title: 'The Thursday Murder Club',
    author: 'Richard Osman',
    description: 'Four unlikely detectives at a retirement village. One unsolved murder. A brand-new very amateur detective agency.',
    price: 15750,
    original_price: 24000,
    isbn: '9781984880963',
    genre: 'Mystery',
    publisher: 'Pamela Dorman Books',
    published_year: 2020,
    pages: 382,
    language: 'English',
    condition: 'good',
    cover_image: 'https://covers.openlibrary.org/b/isbn/9781984880963-L.jpg',
    stock: 8,
    rating: 4.3,
    review_count: 1654,
    featured: false,
    bestseller: false,
    tags: ['mystery', 'cozy', 'humor'],
  },
  {
    title: 'Spare',
    author: 'Prince Harry',
    description: 'The definitive account of the experiences, thoughts, and feelings of the Duke of Sussex.',
    price: 24000,
    original_price: 37500,
    isbn: '9780593593806',
    genre: 'Biography',
    publisher: 'Random House',
    published_year: 2023,
    pages: 416,
    language: 'English',
    condition: 'new',
    cover_image: 'https://covers.openlibrary.org/b/isbn/9780593593806-L.jpg',
    stock: 22,
    rating: 4.1,
    review_count: 3891,
    featured: false,
    bestseller: true,
    tags: ['memoir', 'royalty', 'celebrity'],
  },
  {
    title: 'The Seven Husbands of Evelyn Hugo',
    author: 'Taylor Jenkins Reid',
    description: 'Aging Hollywood movie icon Evelyn Hugo finally decides to tell the truth about her glamorous and scandalous life.',
    price: 17250,
    original_price: 25500,
    isbn: '9781501139239',
    genre: 'Fiction',
    publisher: 'Atria Books',
    published_year: 2017,
    pages: 400,
    language: 'English',
    condition: 'like-new',
    cover_image: 'https://covers.openlibrary.org/b/isbn/9781501139239-L.jpg',
    stock: 16,
    rating: 4.7,
    review_count: 4522,
    featured: true,
    bestseller: true,
    tags: ['historical fiction', 'lgbtq', 'hollywood'],
  },
  {
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    description: 'A lone astronaut must save the earth from disaster while stranded millions of miles from home.',
    price: 18750,
    original_price: 27000,
    isbn: '9780593135204',
    genre: 'Science Fiction',
    publisher: 'Ballantine Books',
    published_year: 2021,
    pages: 480,
    language: 'English',
    condition: 'new',
    cover_image: 'https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg',
    stock: 14,
    rating: 4.8,
    review_count: 2998,
    featured: false,
    bestseller: false,
    tags: ['space', 'adventure', 'hard sci-fi'],
  },
  {
    title: 'It Ends with Us',
    author: 'Colleen Hoover',
    description: "A brave and heartbreaking novel that digs its claws into you and doesn't let go, long after you've finished it.",
    price: 16500,
    original_price: 24000,
    isbn: '9781501110368',
    genre: 'Romance',
    publisher: 'Atria Books',
    published_year: 2016,
    pages: 376,
    language: 'English',
    condition: 'like-new',
    cover_image: 'https://covers.openlibrary.org/b/isbn/9781501110368-L.jpg',
    stock: 19,
    rating: 4.5,
    review_count: 6712,
    featured: false,
    bestseller: true,
    tags: ['contemporary romance', 'emotional', 'domestic abuse'],
  },
  {
    title: 'The Body Keeps the Score',
    author: 'Bessel van der Kolk',
    description: 'A pioneering researcher transforms our understanding of traumatic stress, revealing how it literally reshapes both brain and body.',
    price: 20250,
    original_price: 28500,
    isbn: '9780143127741',
    genre: 'Non-Fiction',
    publisher: 'Penguin Books',
    published_year: 2014,
    pages: 464,
    language: 'English',
    condition: 'good',
    cover_image: 'https://covers.openlibrary.org/b/isbn/9780143127741-L.jpg',
    stock: 10,
    rating: 4.7,
    review_count: 3876,
    featured: false,
    bestseller: true,
    tags: ['psychology', 'trauma', 'health'],
  },
  {
    title: "Harry Potter and the Philosopher's Stone",
    author: 'J.K. Rowling',
    description: 'The book that launched one of the best-selling series of all time. Harry Potter discovers he is a wizard and enters Hogwarts School of Witchcraft and Wizardry.',
    price: 13500,
    original_price: 19500,
    isbn: '9780439708180',
    genre: 'Fantasy',
    publisher: 'Bloomsbury',
    published_year: 1997,
    pages: 309,
    language: 'English',
    condition: 'good',
    cover_image: 'https://covers.openlibrary.org/b/isbn/9780439708180-L.jpg',
    stock: 35,
    rating: 4.9,
    review_count: 12045,
    featured: true,
    bestseller: true,
    tags: ['magic', 'adventure', 'school'],
  },
  {
    title: 'The Power of Now',
    author: 'Eckhart Tolle',
    description: 'A guide to spiritual enlightenment. Tolle describes his transition from despondency to enlightenment and teaches readers how to be free from pain and discover inner peace.',
    price: 18000,
    original_price: 24000,
    isbn: '9781577314806',
    genre: 'Self-Help',
    publisher: 'New World Library',
    published_year: 1997,
    pages: 236,
    language: 'English',
    condition: 'fair',
    cover_image: 'https://covers.openlibrary.org/b/isbn/9781577314806-L.jpg',
    stock: 7,
    rating: 4.4,
    review_count: 2341,
    featured: false,
    bestseller: false,
    tags: ['spirituality', 'mindfulness', 'philosophy'],
  },
  {
    title: 'Normal People',
    author: 'Sally Rooney',
    description: 'The story of mutual fascination, friendship and love between Connell and Marianne, two students moving between the social worlds of rural Ireland.',
    price: 15000,
    original_price: 22500,
    isbn: '9781984822185',
    genre: 'Fiction',
    publisher: 'Faber & Faber',
    published_year: 2018,
    pages: 288,
    language: 'English',
    condition: 'like-new',
    cover_image: 'https://covers.openlibrary.org/b/isbn/9781984822185-L.jpg',
    stock: 13,
    rating: 4.2,
    review_count: 3198,
    featured: false,
    bestseller: false,
    tags: ['contemporary', 'ireland', 'coming-of-age'],
  },
  {
    title: 'Dune',
    author: 'Frank Herbert',
    description: 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world.',
    price: 18000,
    original_price: 27000,
    isbn: '9780441013593',
    genre: 'Science Fiction',
    publisher: 'Ace',
    published_year: 1965,
    pages: 688,
    language: 'English',
    condition: 'good',
    cover_image: 'https://covers.openlibrary.org/b/isbn/9780441013593-L.jpg',
    stock: 20,
    rating: 4.8,
    review_count: 9876,
    featured: false,
    bestseller: true,
    tags: ['epic', 'space opera', 'politics'],
  },
  {
    title: 'Think Again',
    author: 'Adam Grant',
    description: 'The book examines the critical art of rethinking: how to question our own views and encourage others to do the same.',
    price: 19500,
    original_price: 30000,
    isbn: '9781984878106',
    genre: 'Non-Fiction',
    publisher: 'Viking',
    published_year: 2021,
    pages: 320,
    language: 'English',
    condition: 'new',
    cover_image: 'https://covers.openlibrary.org/b/isbn/9781984878106-L.jpg',
    stock: 9,
    rating: 4.5,
    review_count: 1890,
    featured: false,
    bestseller: false,
    tags: ['psychology', 'business', 'thinking'],
  },
  {
    title: 'Gone Girl',
    author: 'Gillian Flynn',
    description: "On the morning of their fifth wedding anniversary, Nick Dunne's wife Amy disappears. Under mounting pressure from the police and the media, the terrible truth begins to unravel.",
    price: 14250,
    original_price: 22500,
    isbn: '9780307588371',
    genre: 'Mystery',
    publisher: 'Crown',
    published_year: 2012,
    pages: 422,
    language: 'English',
    condition: 'good',
    cover_image: 'https://covers.openlibrary.org/b/isbn/9780307588371-L.jpg',
    stock: 11,
    rating: 4.3,
    review_count: 4567,
    featured: false,
    bestseller: false,
    tags: ['thriller', 'psychological', 'marriage'],
  },
  {
    title: "The Subtle Art of Not Giving a F*ck",
    author: 'Mark Manson',
    description: "A counterintuitive approach to living a good life. Mark Manson argues that life's struggles give it meaning, and the key to well-being is not positive thinking.",
    price: 17250,
    original_price: 25500,
    isbn: '9780062457714',
    genre: 'Self-Help',
    publisher: 'HarperOne',
    published_year: 2016,
    pages: 224,
    language: 'English',
    condition: 'like-new',
    cover_image: 'https://covers.openlibrary.org/b/isbn/9780062457714-L.jpg',
    stock: 17,
    rating: 4.4,
    review_count: 5432,
    featured: false,
    bestseller: true,
    tags: ['philosophy', 'humor', 'self-improvement'],
  },
  {
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    description: 'The romantic clash between the opinionated Elizabeth Bennet and her proud beau Mr. Darcy. A timeless classic of English literature.',
    price: 10500,
    original_price: null,
    isbn: '9780141439518',
    genre: 'Fiction',
    publisher: 'Penguin Classics',
    published_year: 1813,
    pages: 432,
    language: 'English',
    condition: 'good',
    cover_image: 'https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg',
    stock: 28,
    rating: 4.7,
    review_count: 15234,
    featured: false,
    bestseller: false,
    tags: ['classic', 'romance', 'regency'],
  },
];

async function seed() {
  console.log('Connecting to Supabase...');

  // Clear existing books
  const { error: deleteError } = await supabase.from('books').delete().neq('id', '');
  if (deleteError) {
    console.error('Failed to clear books:', deleteError.message);
    process.exit(1);
  }
  console.log('Cleared existing books');

  // Insert in batches of 10
  const batchSize = 10;
  let inserted = 0;
  for (let i = 0; i < books.length; i += batchSize) {
    const batch = books.slice(i, i + batchSize);
    const { error } = await supabase.from('books').insert(batch);
    if (error) {
      console.error('Insert error:', error.message);
      process.exit(1);
    }
    inserted += batch.length;
  }

  console.log(`Inserted ${inserted} books successfully`);
}

seed();
